Parameters:
  Int:
    Type: Number
    Default: 500000000

  Float:
    Type: Number
    Default: 12345.6789

  AccountID:
    Type: String
    Default: 0123456789

Resources:
  Bucket1:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Fn::Base64:
          Ref: Cakes

  Bucket2:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Base64
        Ref: Cakes

Outputs:
  Bucket1Arn:
    Value: !GetAtt Bucket1.Arn
  Bucket1Name:
    Value: !Ref Bucket1
  Bucket2Arn:
    Value:
      Fn::GetAtt:
        - Bucket2
        - Arn
